version: "3"
services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - product_list

networks:
  product_list:
    driver: bridge
    