<div class="container errorPage mt-5">
    <div class="row mt-5 d-block align-items-center" style='color: tomato;'>
        <div class="col text-center h-100 w-50 mt-5 m-auto">
            <h2 class="mt-5 h-100" style='font-size: 5rem;'>eRRoR <span style='font-size: 7rem; color: red;'>404</span></h2>
            <h2 class="mt-5 h-100" style='color: #222;'>Page Not found</h2>
            <h4 class="mt-5 h-100"><a href="/">Home</a></h4>
        </div>
    </div>
</div>