<div class="row bootContainer">
    <div class="col-4 mb-3">
        <aside class="bootcamp">
            <h1>BootCamp</h1>
            <div class="links">
                <div class="week">
                    <div class="workshop">
                        <h4>1st Workshop</h4>

                        <a href="../public/projects/greenfox/play-around-with-existing-html-and-css/index.html" target="appereanceSection">play around with existing html and css</a>
                        <hr>

                        <a href="../public/projects/greenfox/velox/index.html" target="appereanceSection">Velox Zerda Lagopus</a>
                        <hr>

                        <a href="../public/projects/greenfox/north-south/index.html" target="appereanceSection">north south</a>
                        <hr>

                        <a href="../public/projects/greenfox/north-east-south-west/index.html" target="appereanceSection">north east south west</a>
                        <hr>

                        <a href="../public/projects/greenfox/text-lists/index.html" target="appereanceSection">text lists</a>
                        <hr>

                        <a href="../public/projects/greenfox/simple-form/index.html" target="appereanceSection">simple form</a>
                        <hr>

                        <a href="../public/projects/greenfox/form2/index.html" target="appereanceSection">complicated form</a>

                        <h4>2nd Workshop</h4>

                        <a href="../public/projects/greenfox/links/index.html" target="appereanceSection">links</a>
                        <hr>

                        <a href="../public/projects/greenfox/pics/index.html" target="appereanceSection">pics</a>
                        <hr>

                        <a href="../public/projects/greenfox/pics-links/index.html" target="appereanceSection">pics links</a>
                        <hr>

                        <a href="../public/projects/greenfox/ground-flexbox/index.html" target="appereanceSection">ground flex box</a>
                        <hr>

                        <a href="../public/projects/greenfox/4-box/index.html" target="appereanceSection">4 boxes</a>
                        <hr>

                        <a href="../public/projects/greenfox/tipikus-weboldal/index.html" target="appereanceSection">typical website</a>
                        <hr>

                        <a href="../public/projects/greenfox/fixed-header/index.html" target="appereanceSection">fixed header</a>
                        <hr>

                        <a href="../public/projects/greenfox/all-together/index.html" target="appereanceSection">all together</a>

                        <h4>3rd Workshop</h4>

                        <a href="../public/projects/greenfox/first-website-top/index.html" target="appereanceSection">first website top</a>
                        <hr>

                        <a href="../public/projects/greenfox/first-website2.0/index.html" target="appereanceSection">first website 2.0</a>
                        <h4>4th Workshop</h4>
                        <a href="../public/projects/greenfox/practice/simple_selectors.html" target="appereanceSection">simplest selector</a>
                        <hr>

                        <a href="../public/projects/greenfox/practice/pseudo_practice.html" target="appereanceSection">pseudo practice</a>
                        <hr>

                        <a href="../public/projects/greenfox/practice/20boxes.html" target="appereanceSection">20 Boxes</a>

                        <h4>5th Workshop - jQuery</h4>
                        <a href="../public/projects/greenfox/jquery/textlists/index.html" target="appereanceSection">texts-lists</a>
                        <hr>

                        <a href="../public/projects/greenfox/jquery/velox/index.html" target="appereanceSection">Velox</a>
                        <hr>

                        <a href="../public/projects/greenfox/jquery/north-east-south-west/index.html" target="appereanceSection">North-East-South-West</a>
                        <hr>

                        <a href="../public/projects/greenfox/jquery/third.html" target="appereanceSection">DOM Manipulation</a>
                        <hr>


                        <a href="../public/projects/greenfox/jquery/counter.html" target="appereanceSection">Counter</a>
                        <hr>

                        <a href="../public/projects/greenfox/jquery/todo.html" target="appereanceSection">Todo app</a>
                        <hr>

                        <a href="../public/projects/greenfox/jquery/gallery/gallery.html" target="appereanceSection">Gallery</a>

                    </div>
                </div>
            </div>
        </aside>
    </div>
    <div class="col-8 align-items-center">
        <section class="bootcampSection">

            <iframe src="" frameborder="0" name="appereanceSection"></iframe>

        </section>

    </div>
</div>