<div class="docsWrapper m-0 w-100">
    <!-- <div class="unt"> -->
    <div class="row justify-content-around">
        <div class="col-3 item">
            <a class="dox" href="../public/docs/Web_Lebenslauf_Horvath.pdf">Lebenslauf</a>
        </div>
        <div class="col-3 item">
            <a class="dox" href="../public/docs/Bewerbungschreiben.pdf">Bewerbungsschreiben</a>
        </div>
        <div class="col-3 item">
            <a class="dox" href="../public/docs/Codecademy.pdf">Web Development Certificate</a>
            <hr><small style="font-size: 1rem;">Codecademy</small>
        </div>
    </div>
    <div class="row">
        <div id="contact" class="cont col-6">
            <p>
                <b>Peter Horvath</b><br>Schmiedengasse 6<br>2502 Biel/Bienne<br>+41 77 265 7969<br>
                <a class="dox" href="mailto:gkipeter@gmail.com">gkipeter@gmail.com</a>
            </p>
        </div>
    </div>

    <div class="row mt-5 mb-0">
        <div class="containerx sub soclink col">
            <div class="frame">

                <a href="https://github.com/HunCage" class="btnSoc">
                    <i class="fab fa-github fabX" aria-hidden="true" style="color: black;" target="_blank"></i>
                    <small>GitHub</small>
                </a>

                <a href="https://www.freecodecamp.org/huncage" class="btnSoc" target="_blank">
                    <i class="fab fa-free-code-camp fabX" aria-hidden="true" style="color: black;" target="_blank"></i>
                    <small>FreeCodeCamp</small>
                </a>

                <a href="https://www.codecademy.com/profiles/peterHorvath6498374231" class="btnSoc" target="_blank">
                    <i class="fab fa-creative-commons fabX" aria-hidden="true" style="color: black;"></i>
                    <small>CodeCademy</small>
                </a>

                <a href="https://stackoverflow.com/users/13264574/huncage" class="btnSoc" target="_blank">
                    <i class="fab fa-stack-overflow fabX" aria-hidden="true" style="color: rgb(224, 123, 8);"></i>
                    <small>StackOverflow</small>
                </a>

                <a href="https://www.sololearn.com/Profile/13040652" class="btnSoc" target="_blank">
                    <i class="fas fa-spinner spin spinX" aria-hidden="true" style="color: rgba(159, 223, 56, 0.877);"></i>
                    <small>SoloLearn</small>
                </a>
            </div>
        </div>
    </div>
    <!-- </div> -->
</div>