<!-- Footer -->
<!--  class='fixed-bottom' -->
<footer class="bg-dark page-footer text-center text-warning small">
    <!-- Grid container -->
    <div class="footer-container h-25">
        <div class="container m-auto p-1 align-content-center h-25 justify-content-center text-center footer">
            <!-- Section: Social media -->
            <section class="mb-2 text-warning footerSocialButtons mr-4">
                <!-- Facebook -->
                <a class="btn btn-outline-light btn-floating m-1 text-primary" href="http://www.facebook.com" role="button" target="_blank"><i class="fab fa-facebook-f"></i></a>

                <!-- Twitter -->
                <a class="btn btn-outline-light btn-floating m-1 text-primary" href="http://www.twitter.com" role="button" target="_blank"><i class="fab fa-twitter"></i></a>

                <!-- Google -->
                <a class="btn btn-outline-light btn-floating m-1 text-danger" href="http://www.google.ch" role="button" target="_blank"><i class="fab fa-google"></i></a>

                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1 text-danger" href="http://www.instragram.com" role="button" target="_blank"><i class="fab fa-instagram"></i></a>

                <!-- Linkedin -->
                <a class="btn btn-outline-light btn-floating m-1 text-primary" href="http://www.linkedin.com" role="button" target="_blank"><i class="fab fa-linkedin-in"></i></a>

                <!-- Github -->
                <a class="btn btn-outline-light btn-floating m-1" href="http://www.github.com" role="button" target="_blank"><i class="fab fa-github"></i></a>
            </section>
            <!-- Section: Social media -->

            <!-- Section: Form -->
            <!-- <section class="">
                <form action=""> -->
                    <!--Grid row-->
                    <!-- <div class="row d-flex justify-content-center"> -->
                        <!--Grid column-->
                        <!-- <div class="col-auto">
                            <p class="pt-2">
                                <strong>Sign up for our newsletter</strong>
                            </p>
                        </div> -->
                        <!--Grid column-->

                        <!--Grid column-->
                        <!-- <div class="col-md-5 col-12"> -->
                            <!-- Email input -->
                            <!-- <div class="form-outline form-white mb-3">
                                <input type="email" id="form5Example2" class="form-control" />
                                <label class="form-label" for="form5Example2">Email address</label>
                            </div>
                        </div> -->
                        <!--Grid column-->

                        <!--Grid column-->
                        <!-- <div class="col-auto"> -->
                            <!-- Submit button -->
                            <!-- <button type="submit" class="btn btn-outline-light mb-4">
                                Subscribe
                            </button>
                        </div> -->
                        <!--Grid column-->
                    <!-- </div> -->
                    <!--Grid row-->
                <!-- </form> -->
            <!-- </section> -->
            <!-- Section: Form -->

            <!-- Section: Text -->
            <section class="mb-2">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
                </p>
            </section>
            <!-- Section: Text -->

            <!-- Section: Links -->
            <section class="h-25">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Learn</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="http://www.freecodecamp.org" target="_blank" class="text-danger">FreeCodeCamp</a>
                            </li>
                            <li>
                                <a href="http://www.sololearn.com" target="_blank" class="text-danger">SoloLearn</a>
                            </li>
                            <li>
                                <a href="http://www.codecademy.com" target="_blank" class="text-danger">CodeCademy</a>
                            </li>
                            <li>
                                <a href="http://www.https://www.w3schools.com/" target="_blank" class="text-danger">w3Schools</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Learn</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="https://scrimba.com" class="text-white" target="_blank">Scrimba</a>
                            </li>
                            <li>
                                <a href="https://www.simplilearn.com/tutorials/" class="text-white" target="_blank">Simplilearn</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white" target="_blank">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </section>
            <!-- Section: Links -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3 fooFooter" style="background-color: rgba(0, 0, 0, 0.2);">
            © <?= date("Y"); ?> Copyright:
            <a class="footerLink text-purple" href="https://getbootstrap.com/">Bootstrap</a>
        </div>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->