<main class="kidsWrapper">
    <!-- <div class="row"> -->
    <aside id="mySidenav" class="kidsAside sidenav bg-dark z-index-3">
        <!-- <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a> -->
        <a href="#">About</a>
        <a href="#">Services</a>
        <a href="#">Clients</a>
        <a href="#">Contact</a>
    </aside>
    <section class="kidsSection mt-5" id="main">
        <div class="row d-flex">

            <div class="col">
                <iframe class="kidszoneIframe" style="width: 85%; height: 60vh" src="..\public\projects\flashcards\index.php" frameborder="0"></iframe>
            </div>

            <div class="col pokemon mr-2">
                <iframe class="kidszoneIframe" src="..\public\projects\pokeAPI\index.html" frameborder="0" style="width: 100%; height: 35vh">

                </iframe>

            </div>
        </div>

    </section>
    <!-- </div> -->
</main>