<!-- welcome Section -->

<div class="welcome-section" id="home">
    <h1 class="welcsec"><strong>Willkommen, an meine Webseite</strong></h1>
    <p class="welcsec para">Ich bin Peter Web-Designer/Web-Developer</p>
    <a href="/unterlagen"><img src="../public/img/ich.jpg" class="img" alt="ich"></a>
</div>

<div class="wrap row">
    <!-- Skill Section -->
    <div class="col-6 table">
        <table>
            <tr>
                <th colspan="2">My Skills</th>
            </tr>

            <tr>
                <td><i class="fab fa-html5 fa-2x tico"></i>HTML</td>
                <td><progress max="100" value="80"></progress></td>
            </tr>

            <tr>
                <td><i class="fab fa-css3 fa-2x tico"></i>CSS</td>
                <td><progress max="100" value="65"></progress></td>
            </tr>

            <tr>
                <td><i class="fab fa-css3 fa-2x tico"></i>SASS</td>
                <td><progress max="100" value="65"></progress></td>
            </tr>

            <tr>
                <td><i class="fab fa-bootstrap fa-2x tico"></i>Bootstrap</td>
                <td><progress max="100" value="40"></progress></td>
            </tr>

            <tr>
                <td><i class="fab fa-js-square fa-2x tico"></i>JavaScript</td>
                <td><progress max="100" value="40"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-code fa-2x tico"></i>jQuery</td>
                <td><progress max="100" value="20"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-code fa-2x tico"></i>NodeJS</td>
                <td><progress max="100" value="20"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-gamepad fa-2x tico"></i>PhaserJs</td>
                <td><progress max="100" value="20"></progress></td>
            </tr>

            <tr>
                <td><i class="fab fa-php fa-2x tico"></i>PHP</td>
                <td><progress max="100" value="10"></progress></td>
            </tr>

            <!-- </table>

        <table> -->
            <tr>
                <th colspan="2">My Skills</th>
            </tr>

            <tr>
                <td><i class="fab fa-react fa-2x tico"></i>React</td>
                <td><progress max="100" value="20"></progress></td>
            </tr>

            <tr>
                <td><i class="fab fa-vuejs fa-2x tico"></i>Vue</td>
                <td><progress max="100" value="15"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-database fa-2x tico"></i>MySQL</td>
                <td><progress max="100" value="40"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-database fa-2x tico"></i>MongoDB</td>
                <td><progress max="100" value="40"></progress></td>
            </tr>

            <tr>
                <td><i class="fab fa-git-square fa-2x tico"></i>GitHub</td>
                <td><progress max="100" value="35"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-photo-video fa-2x tico"></i>Photoshop</td>
                <td><progress max="100" value="40"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-photo-video fa-2x tico"></i>Postman</td>
                <td><progress max="100" value="40"></progress></td>
            </tr>

            <tr>
                <td><i class="fas fa-photo-video fa-2x tico"></i>Linux</td>
                <td><progress max="100" value="40"></progress></td>
            </tr>

            <tr>
                <td><i class="far fa-newspaper fa-2x tico"></i>QuarkXpress</td>
                <td><progress max="100" value="45"></progress></td>
            </tr>

        </table>

    </div>
    <div class="col-6">
        <!-- Sideboard -->
        <aside class="side" id="about-me">
            <button type="button" class="btntxt button btnx" onclick="noText()">Mehr info</button>
            <div id="text">
                <p>
                    <strong>Mein Name ist Peter und ich suche neue Herasuforderungen als Quereinsteger in IT-Bereich/Web-Developer.</strong>
                    <hr>
                    <br class="ti">Bis Anfang 2020 war ich in Baubranche in der letzen Zeit als Vorarbeiter und auch Baustellenleiter tätig. Wegen meine plötzlich veränderte Gesundheitsstand brauche ich nach neue Tätigkeit zu schauen und dann möchte ich
                    dass mit meiner kindheitliche Hobby und Leidenschaft kombinieren.<br>
                    <br> Im Jahr 2019 habe ich die schlechte gesundheitliche wirkung von meine bisherige Arbeit gemerkt und dann habe ich neben der Arbeit und in meiner Freizeit das Web-Desingner/Web-Developer Geheimnisse Studieren an.<br> Das bedutet
                    ich habe Onlinekurse bei SoloLearn, CodeCademy und bei FreeCodeCamp(teilweise) auch fertig gemacht und erstellte auch einige kleine Projekte.<br>
                </p>
                <br>
                <a href="login.html" target="_blank">Lebenslauf/Kontakt</a>
            </div>
        </aside>
    </div>

    <div class="arrow">
        <a href="#" title="Back to Top"><span class="fas fa-angle-up"></span></a>
    </div>
</div>