<!-- Project tiles -->
<div class="wrapper row">
    <div class="projects col-6">
        <h2 class="">Projekte</h2>
    </div>

    <!-- <div class="projects col-6">
        <h4 class="">HTML</h4>
    </div> -->

    <div class="container col-12">
        <div class="cards" id="projects">

            <?php foreach ($params['projects'] as $project) : ?>
                <div class="grid-item card">
                    <div class="card text-center">
                        <img src="<?= $project['project_image'] ?>" class="card-img" alt="<?= $project['project_name'] ?>">
                        <div class="card-body">
                            <h5 class="card-title"><?= $project['project_title'] ?></h5>
                            <p class="card-text">
                                <?= $project['project_description'] ?>
                            </p>
                            <a href="<?= $project['project_link'] ?>" class="button btnx" target="_blank">ausprobieren</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>

            <!-- <div class="projects col-6">
        <h4 class="">JavaScript</h4>
    </div>

    <div class="container col-12">
        <div class="cards" id="projects">

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"></h5>
                        <p class="card-text">
                            
                        </p>
                        <a href="" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

    <div class="projects col-6">
        <h4 class="">Projekte</h4>
    </div>

    <div class="container col-12">
        <div class="cards" id="projects">

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"></h5>
                        <p class="card-text">
                            
                        </p>
                        <a href="" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div> -->

        </div>
    </div>
</div>

<div class="arrow">
    <a href="#" title="Back to Top"><span class="fas fa-angle-up"></span></a>
</div>