<!-- Project tiles -->
<div class="wrapper row">
    <div class="projects col-6">

        <h2 class="">Projekte</h2>
    </div>

    <div class="container col-12">
        <div class="cards" id="projects">

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/guess.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Guess a Number</h5>
                        <p class="card-text">
                            Ich dachte auf ein Nummer...
                        </p>
                        <a href="..\public\projects\guessanumber\guess.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/barcode.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Barcode generator</h5>
                        <p class="card-text">
                            Eigene Barcode erstellen...
                        </p>
                        <a href="..\public\projects\barcode_generator\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/calc.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Rechner</h5>
                        <p class="card-text">
                            Einfaches Rechner...
                        </p>
                        <a href="..\public\projects\Calculator\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/gallery.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Photo Gallery</h5>
                        <p class="card-text">
                            Bilder zu betrachten...
                        </p>
                        <a href="..\public\projects\image_slider\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/imgallery.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Image Gallery</h5>
                        <p class="card-text">
                            Photogallerie...
                        </p>
                        <a href="..\public\projects\simple_image_gallery\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/todo.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">To Do App</h5>
                        <p class="card-text">
                            Todo app...
                        </p>
                        <a href="..\public\projects\todo_app_draggable\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/galaxy.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Our Galaxy</h5>
                        <p class="card-text">
                            Webseite mit Image map aus unseres Sonnensysteme...
                        </p>
                        <a href="..\public\projects\galaxy\imgmap.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/qr.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">QR Code Generator</h5>
                        <p class="card-text">
                            Eigenen QR Code erstellen...
                        </p>
                        <a href="..\public\projects\qr_code_generator\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/wechsler.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Devisen Kurs Wechsler</h5>
                        <p class="card-text">
                            Devisen umrechner...
                        </p>
                        <a href="..\public\projects\wechsler\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

            <div class="grid-item card">
                <div class="card text-center">
                    <img src="../public/img/snake.jpg" class="card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Snake Spiel</h5>
                        <p class="card-text">
                            Altes Spiel in Nokia Art.<br> Mit den Kursortasten bewegen<br> Sie sich die Schlange...
                        </p>
                        <a href="..\public\projects\snake\index.html" class="button btnx" target="_blank">ausprobieren</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="arrow">
    <a href="#" title="Back to Top"><span class="fas fa-angle-up"></span></a>
</div>