<div class="container formContainer mt-5 mb-5  w-50">
    <div class="card formWrapper p-3 mt-5 mb-5 bg-white">
        <div class="jumbotron text-center bg-dark">
            <h5 class="text-warning">Sie müssen angemeldet sein, um diesen Inhalt anzeigen zu können</h5>
            <h2 class="text-warning">Legen Sie ein neue Account an</h2>
        </div>

        <form action="/register" method="POST" class="form-group" class="postForm" onkeyup="regValidation()" onsubmit="return regValidation();">
        <?php if (isset($_GET['info'])) : ?>
                <?php if ($_GET['info'] === 'invalidRegister') : ?>
                    <div class="alert alert-danger">
                        Benutzername oder email ist schon existiert!<br />
                        Oder die Angaben falsche sind!
                    </div>
                <?php endif; ?>

                <?php if ($_GET['info'] === 'isSuccess') : ?>
                    <div class="alert alert-success">
                        Registration ist erfolgreich abgeschlossen!
                    </div>
                <?php endif; ?>

                <?php if ($_GET['info'] === 'isLoggedIn') : ?>
                    <div class="alert alert-primary">
                        Erfolgreich eingeloggt!
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <div class="inputBox">
                <label for="username" class="w-100 mb-0">username</label>
                <input class="form-control" type="text" name="username" id="username" placeholder="Benutzername">
                <span class="indicatorUser"></span>
                <small class="textUser mt-0"></small>
                <!-- <i class="fa fa-check-circle" id="check"></i>
                    <i class="fa fa-times-circle" id="times"></i> -->
                <!-- </div> -->
            </div>

            <div class="inputBox">
                <label for="email" class="w-100">email</label>
                <input class="form-control" type="email" name="email" id="email" placeholder="Email">
                <span class="indicatorEmail"></span>
                <small class="textEmail"></small>
                <!-- <i class="fa fa-check-circle" id="check"></i>
                    <i class="fa fa-times-circle" id="times"></i> -->
            </div>

            <div class="inputBox">
                <label for="password" class="w-100">password</label>
                <input class="form-control" type="password" name="password" id="password" placeholder="Passwort">
                <span class="indicatorPassword"></span>
                <small class="textPassword"></small>
                <!-- <i class="fa fa-check-circle" id="check"></i>
                    <i class="fa fa-times-circle" id="times"></i> -->
            </div>
    <!-- </div> -->

    <button type="submit" id="submit" class="btn btn-primary form-control mt-3">Registration</button>
    </form>

    <p>
        Haben Sie schon ein Account?
        <a href="/login">einloggen</a>
    </p>
</div>
</div>
<script src="public/js/validation.js"></script>