<!-- <#?php include "edit/index.html" ?> -->
<div class="editMain">
    <header>
        <nav>
            <ul>
                <li><a href="#">Von mir</a></li>
                <li><a href="#">Unterlagen</a>
                <li><a href="#">Fähigkeiten</a></li>
                <li><a href="#">Kontakt</a></li>
            </ul>
        </nav>
    </header>

    <div class="row">
        <div>
            <h1 class="gruss">
                Ich begrüsse sie herzlich auf meine Vorstellungssite
            </h1>
        </div>
        <div class="texth3">
            <p>
                <img class="pics0" src="../public/img/pics/images.jpg" style="float:left" alt="Ich selbst">Ich möchte mich kurz vorstellen. Mein Name ist Edit Horvathne Fodor. Ich bin 52 Jahre alt und habe 2 Kinder.In der Schweiz lebe ich schon seit 2 Jahren. In
                der Pflegebranche habe ich schon über 30 Jahren Erfahrung.In meiner Heimat war ich als Diplomierter Krankenschwester tätig und habe mehreren Jahren in Nachtdienst gearbeitet.
            </p>
            <p>In 2015 nach meiner Elternzeit suchte ich nach einer neuen Herausforderung und ich hatte eine gute Gelegenheit in Deutschland mit eine Intensiv Deutsch Kurs kombiniert gefunden. Nach ein halbes Jahr konnte ich leider den B2 Niveau nicht erreichen
                die man als Pflegerin braucht von daher habe ich als Pflegehelferin in eine Rehaklinik im Bad Peterstal gearbeitet bis 2018. Während diese Zeit konnte ich meine Sprachkenntnisse und meine Kommunikationsfähigkeiten mehr verbessern.</p>
            <p><img class="pics2" src="../public/img/pics/first-aid-2653869__480.png" alt="Erste Hilfe" style="float:right">Im August 2018 bin ich mit meiner Familie nach Schweiz umgezogen, weil mein Mann schon 1 Jahr lang in der Schweiz gearbeitet hat. Am ersten August
                begann ich in Biel in Alterswohnheim Büttemberg als Pflegehelferin zu arbeiten und nachher habe ich dort auch in dem Nachtdienst gearbeitet.
            </p>
            <p>Nun ist es wieder so weit und ich suche nach einer neuen Herausforderung. Mit meinen langjährigen Berufserfahrungen in der Pflegebrache und auch als in Betreuung würde ich Ihr Team gerne stärken. Ich bin flexibel und zuverlässig und ich kann
                in verschiedenen Sichten arbeiten zum Beispiel auch am Wochenende.
            </p>
            <p>Sehr gerne möchte ich Sie in einem Vorstellungsgespräch mich Persönlich von meinem Stärken überzeugen. Gerne erwarte ich Ihren Bescheid und danke ihnen schon Voraus und bedanke mich für ihre besuch auf meiner Website.
            </p>
            <br />
            <hr /> <br />
        </div>
    </div>

    <div class="row expSection">
        <div class="col jobSection">
            <h2 class="grussa"><span>Berufliche Erfahrungen</span></h2>
            <ul class="eigens">
                <li>Krankenschwester
                </li>
                <li>Pflegehelferin
                </li>
                <li>Spitex
                </li>
                <li>Hystolgiaen Assistentin
                </li>
                <li>Nachtwache
                </li>
            </ul>
        </div>
        <img id="fahig" class="pics" src="../public/img/pics/nurse1_1280.png" alt="Schwester">
        <div class="col jobSection">
            <p><span>Eigenschaften</span></p>
            <ul class="eigens eig ">
                <li>Empathie
                </li>
                <li>Gute umgang zu Menschen
                </li>
                <li>Verantwortungsbewusst
                </li>
                <li>Flexibel
                </li>
                <li>Pünktlichkeit
                </li>
                <li>Belastbar
                </li>
                <li>Spitex
                </li>
            </ul>
        </div>
    </div>

    <hr />

    <div class="editDocSection m-auto justify-content-space-around">

        <div class="row docs m-auto justify-content-space-around">
            <div class="col m-auto docs">
                <a href="../public/docs/unterlagen/Lebenslauf.pdf" target="_blank" title="Mein Lebenslauf betrachten/herunterladen"><img class="unterlag" src="../public/img/pics/_unterlagen/lebens.jpg" alt="Lebenslauf"></a>
            </div>

            <div class="col m-auto docs">
                <a href="../public/docs/unterlagen/Arbeitszeugnis_Buttemberg.pdf" title="Arbeitszeugnis betrachten/herunterladen"><img src="../public/img/pics/_unterlagen/butten.jpg" class="unterlag" alt="Arbeitszeugnis"></a>
            </div>

            <div class="col m-auto docs">
                <a href="../public/docs/unterlagen/Arbeitszeugnis_Mediclin.pdf" title="Arbeitszeugnis betrachten/herunterladen"><img src="../public/img/pics/_unterlagen/medic.jpg" class="unterlag" alt="arbeitszeugnis"></a>
            </div>
        </div>

        <div class="row justify-content-space-around">
            <div class="col m-auto docs">
                <a href="../public/docs/unterlagen/Zeugnis.pdf" title="Fachschule Zeugnis betrachten/herunterladen"><img src="../public/img/pics/_unterlagen/zeugnis.jpg" class="unterlag" alt="Zeugnis"></a>
            </div>

            <div class="col m-auto docs">
                <a href="../public/docs/unterlagen/Certificate_Conformity.pdf" title="Certificate betrachten/herunterladen"><img src="../public/img/pics/_unterlagen/cert.jpg" class="unterlag" alt="Certificate"></a>
            </div>

            <div class="col m-auto docs">
                <a href="../public/docs/unterlagen/srk.pdf" title="SRK Bestätigung betrachten/herunterladen"><img src="../public/img/pics/_unterlagen/srk.jpg" class="unterlag" alt="SRK Bestätigung"></a>
            </div>
        </div>

        <div class="row justify-content-space-around">
            <div class="col-4 m-auto docs">
                <a href="../public/docs/unterlagen/Dipmlome.pdf" title="Diplome betrachten/herunterladen"><img src="../public/img/pics/_unterlagen/diplom.jpg" class="unterlag" alt="Diplome"></a>
            </div>
        </div>

    </div>

    <div class="editContactSection">
        <div class="row justify-content-space-evenly">
            <div class="col">
                <hr />
                <p id="contact"><b>Kontakt:</b><img class="pics1" src="../public/img/pics/images1.jpg" style="float: right" alt="">
                </p>
                <p>Edit, Horvathne Fodor<br></p>
                <p>Kt. Bern, Biel/Bienne</p>
                <p>Tel.: 078 789 9233</p>
                <br>
                <p><a href="mailto:algopiryn500.ef@gmail.com">algopiryn500.ef@gmail.com</a></p>
                <hr />
            </div>
        </div>
    </div>

    <div class="arrow">
        <a href="#" title="Back to Top"><span class="fas fa-angle-up"></span></a>
    </div>

</div>